CREATE TABLE IF NOT EXISTS `user_prefs` (
  `user_id` BIGINT PRIMARY KEY,
  `work_days` VARCHAR(20) DEFAULT '1,2,3,4,5',
  `work_date_overrides` VARCHAR(500) DEFAULT '',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
