CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `openid` VARCHAR(64) NOT NULL UNIQUE,
  `nickname` VARCHAR(64) DEFAULT '',
  `avatar_url` VARCHAR(512) DEFAULT '',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user_prefs` (
  `user_id` BIGINT PRIMARY KEY,
  `work_days` VARCHAR(20) DEFAULT '1,2,3,4,5',
  `work_date_overrides` VARCHAR(500) DEFAULT '',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `user_config` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `salary_type` VARCHAR(16) NOT NULL DEFAULT 'MONTHLY',
  `monthly_salary` DECIMAL(10,2) DEFAULT 0,
  `hourly_rate` DECIMAL(10,2) DEFAULT 0,
  `daily_work_hours` DECIMAL(4,2) DEFAULT 8,
  `work_start_time` TIME DEFAULT '09:00:00',
  `work_end_time` TIME DEFAULT '18:00:00',
  `lunch_start` TIME DEFAULT '12:00:00',
  `lunch_end` TIME DEFAULT '13:00:00',
  `work_days_per_week` INT DEFAULT 5,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `daily_record` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `record_date` DATE NOT NULL,
  `total_earned` DECIMAL(10,2) DEFAULT 0,
  `is_workday` TINYINT(1) DEFAULT 1,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uk_user_date` (`user_id`, `record_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
